### ISSUE TITLE
Option to automatically update session for current branch after switch

### ISSUE THREAD

**Issue by fizvlad** [mangano-ito/git-branch-wise-session#16]
Would be nice to have a checkbox 'Automatically update branch session before switch', since I sometimes forget to manually do this

This feature was done in [Restore Git Branch Tabs](https://github.com/gkotas/vscode-restore-git-branch-tabs), but this extension is broken and no longer supported

**Comment by mangano-ito** [comment]
Thank you for the feature request and your patience!

This feature is supported in version 1.0.0 (thanks to the contribution in #18).
Update the extension and see it works. I hope you're happy with it.

---

Issue now closed as resolved.
