### ISSUE TITLE
Load save session files in the same tab, instead of 1 tab for each file

### ISSUE THREAD

**Issue by catarino** [mangano-ito/git-branch-wise-session#3]
The files seem to be instantly loaded one by one but only last one is kept.

https://user-images.githubusercontent.com/609172/103776282-1f0fae00-5027-11eb-9487-a4737c4a9919.mov

VS Code Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

**Comment by catarino** [comment]
It will be great if it works as advertised. 

Thank you in advance :)

**Comment by igors-levkovs** [comment]
I confirm, it loads tabs, but it doesn't pin them, so only one is kept. VS Code v 1.56.2

**Comment by deepaktalwardt** [comment]
This issue has been fixed in the latest version 0.3.0. Please give it a try again.

**Comment by catarino** [comment]
Great. Thx!

**Comment by mangano-ito** [comment]
Thank you!

**Comment by catarino** [comment]
I confirm it's working as expected. 

Thank you.

Have a great 2022 all! :)
